{
  "apiVersion": "v1",
  "kind": "List",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "PersistentVolumeClaim",
      "metadata": {
        "name": "dali-live"
      },
      "spec": {
        "accessModes": [
          "ReadWriteOncePod"
        ],
        "storageClassName": "operator-provisioned",
        "resources": {
          "requests": {
            "storage": "10Gi"
          }
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "PersistentVolumeClaim",
      "metadata": {
        "name": "dali-backup"
      },
      "spec": {
        "accessModes": [
          "ReadWriteOncePod"
        ],
        "storageClassName": "operator-provisioned",
        "resources": {
          "requests": {
            "storage": "100Gi"
          }
        }
      }
    }
  ]
}
